export const actionType = {
  START_REQUEST_FETCHING: 'START_REQUEST_FETCHING',
  RECEIVE_MOVIE_LIST: 'RECEIVE_MOVIE_LIST',
  RECEIVE_MOVIE_INFO: 'RECEIVE_MOVIE_INFO',
  SAVE_INPUT_QUERY: 'SAVE_INPUT_QUERY',
};
