export const actionType = {
  START_REQUEST_FETCHING: 'START_REQUEST_FETCHING',
  RECEIVE_SEARCHED_MOVIE_LIST: 'RECEIVE_SEARCHED_MOVIE_LIST',
  RECEIVE_POPULAR_MOVIE_LIST: 'RECEIVE_POPULAR_MOVIE_LIST',
  RECEIVE_UPCOMING_MOVIE_LIST: 'RECEIVE_UPCOMING_MOVIE_LIST',
  RECEIVE_TOP_RATED_MOVIE_LIST: 'RECEIVE_TOP_RATED_MOVIE_LIST',
  RECEIVE_MOVIE_INFO: 'RECEIVE_MOVIE_INFO',
  SAVE_INPUT_QUERY: 'SAVE_INPUT_QUERY',
};
